package com.gameserver.bazoo.msg;

import java.util.HashMap;
import java.util.Map;

import com.gameserver.common.msg.MessageType;
import com.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class BazooMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_BAZOO_CHANGE_NAME, CGBazooChangeName.class);
		map.put(MessageType.CG_BAZOO_HEART_BEAT, CGBazooHeartBeat.class);
		map.put(MessageType.CG_MODE_CHOSE, CGModeChose.class);
		map.put(MessageType.CG_ROOM_CREATE, CGRoomCreate.class);
		map.put(MessageType.CG_ROOM_PRI_SEARCH, CGRoomPriSearch.class);
		map.put(MessageType.CG_ROOM_PRI_List, CGRoomPriList.class);
		map.put(MessageType.CG_ROOM_PRI_JOIN, CGRoomPriJoin.class);
		map.put(MessageType.CG_ROOM_PUB_JOIN, CGRoomPubJoin.class);
		map.put(MessageType.CG_ROOM_ENTER, CGRoomEnter.class);
		map.put(MessageType.CG_ROOM_OUT, CGRoomOut.class);
		map.put(MessageType.CG_DICE_SINGLE_SWING, CGDiceSingleSwing.class);
		map.put(MessageType.CG_TALK_BIG, CGTalkBig.class);
		map.put(MessageType.CG_ROB_OPEN, CGRobOpen.class);
		map.put(MessageType.CG_GUESS_BIG_SMALL, CGGuessBigSmall.class);
		map.put(MessageType.CG_COW_SINGLE_SWING, CGCowSingleSwing.class);
		map.put(MessageType.CG_SHOW_HAND_SINGLE_SWICH, CGShowHandSingleSwich.class);
		map.put(MessageType.CG_SHOW_HAND_SINGLE_SWICH_CANCEL, CGShowHandSingleSwichCancel.class);
		map.put(MessageType.CG_SHOW_HAND_SINGLE_SWING, CGShowHandSingleSwing.class);
		map.put(MessageType.CG_BLACK_WHITE_CALL_NUM, CGBlackWhiteCallNum.class);
		map.put(MessageType.CG_BAZOO_HALL_STATUS, CGBazooHallStatus.class);
		map.put(MessageType.CG_BAZOO_MAGIC_FACE, CGBazooMagicFace.class);
		map.put(MessageType.CG_BAZOO_NEWGUY_PROCESS, CGBazooNewguyProcess.class);
		map.put(MessageType.CG_BAZOO_BOQU, CGBazooBoqu.class);
		map.put(MessageType.CG_BAZOO_FACEBOOK_ADD_GOLD, CGBazooFacebookAddGold.class);
		return map;
	}

}
