package com.gameserver.gift.msg;

import java.util.HashMap;
import java.util.Map;

import com.gameserver.common.msg.MessageType;
import com.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class GiftMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_REQUEST_GIFT, CGRequestGift.class);
		map.put(MessageType.CG_REQUEST_GIFT_TIME_END, CGRequestGiftTimeEnd.class);
		map.put(MessageType.CG_NEW_COMER_GIFT, CGNewComerGift.class);
		return map;
	}

}
