package com.gameserver.slot.msg;

import java.util.HashMap;
import java.util.Map;

import com.gameserver.common.msg.MessageType;
import com.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class SlotMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_SLOT_ENTER, CGSlotEnter.class);
		map.put(MessageType.CG_SLOT_ENTER_ROOM, CGSlotEnterRoom.class);
		map.put(MessageType.CG_SLOT_OUT, CGSlotOut.class);
		map.put(MessageType.CG_SLOT_SLOT, CGSlotSlot.class);
		map.put(MessageType.CG_FREE_SLOT_REWARD, CGFreeSlotReward.class);
		map.put(MessageType.CG_SLOT_GET_LIST, CGSlotGetList.class);
		map.put(MessageType.CG_SLOT_TOURNAMENT_START, CGSlotTournamentStart.class);
		map.put(MessageType.CG_SLOT_TOURNAMENT_CLOSE, CGSlotTournamentClose.class);
		map.put(MessageType.CG_TOURNAMENT_GET_LIST, CGTournamentGetList.class);
		map.put(MessageType.CG_SLOT_GET_RANK, CGSlotGetRank.class);
		map.put(MessageType.CG_SNG_RANK_INFO, CGSngRankInfo.class);
		map.put(MessageType.CG_SLOT_TYPE12_CHOOSE, CGSlotType12Choose.class);
		map.put(MessageType.CG_SLOT_TYPE12_FREE, CGSlotType12Free.class);
		map.put(MessageType.CG_SLOT_TYPE13_BOUNS_PRIZE, CGSlotType13BounsPrize.class);
		map.put(MessageType.CG_SLOT_TYPE15_BOUNS, CGSlotType15Bouns.class);
		map.put(MessageType.CG_SLOT_TYPE19_SCATTER, CGSlotType19Scatter.class);
		map.put(MessageType.CG_SLOT_TYPE21_BOUNS, CGSlotType21Bouns.class);
		map.put(MessageType.CG_SLOT_TYPE22, CGSlotType22.class);
		map.put(MessageType.CG_SLOT_TYPE23_INIT_REWARD, CGSlotType23InitReward.class);
		map.put(MessageType.CG_SLOT_TYPE24_BOUNS_PRIZE, CGSlotType24BounsPrize.class);
		map.put(MessageType.CG_SLOT_TYPE24_BOUNS_GAME_GO, CGSlotType24BounsGameGo.class);
		map.put(MessageType.CG_SLOT_TYPE25_BOUNS, CGSlotType25Bouns.class);
		map.put(MessageType.CG_SLOT_TYPE26_BOUNS, CGSlotType26Bouns.class);
		map.put(MessageType.CG_SLOT_TYPE28_BOUNS, CGSlotType28Bouns.class);
		map.put(MessageType.CG_SLOT_TYPE29_BOUNS, CGSlotType29Bouns.class);
		map.put(MessageType.CG_SLOT_TYPE30_BOUNS, CGSlotType30Bouns.class);
		map.put(MessageType.CG_SLOT_TYPE31_BOUNS, CGSlotType31Bouns.class);
		map.put(MessageType.CG_SLOT_TYPE38_BONUS, CGSlotType38Bonus.class);
		map.put(MessageType.CG_GET_SLOT_CACHEMSG, CGGetSlotCachemsg.class);
		map.put(MessageType.CG_DEMO_TYPE, CGDemoType.class);
		return map;
	}

}
