package com.gameserver.bazoorank.msg;

import java.util.HashMap;
import java.util.Map;

import com.gameserver.common.msg.MessageType;
import com.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class BazoorankMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_BAZOO_RANK_TOTAL_GOLD_REQUEST, CGBazooRankTotalGoldRequest.class);
		map.put(MessageType.CG_BAZOO_RANK_REQUEST, CGBazooRankRequest.class);
		return map;
	}

}
