package com.gameserver.texas.msg;

import java.util.HashMap;
import java.util.Map;

import com.gameserver.common.msg.MessageType;
import com.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class TexasMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_TEXAS_LIST, CGTexasList.class);
		map.put(MessageType.CG_JOIN_TEXAS_ROOM_ID, CGJoinTexasRoomId.class);
		map.put(MessageType.CG_JOIN_TEXAS, CGJoinTexas.class);
		map.put(MessageType.CG_LEAVE_TEXAS, CGLeaveTexas.class);
		map.put(MessageType.CG_TEXAS_LOOK, CGTexasLook.class);
		map.put(MessageType.CG_TEXAS_FOLLOW, CGTexasFollow.class);
		map.put(MessageType.CG_TEXAS_ADD_BET, CGTexasAddBet.class);
		map.put(MessageType.CG_TEXAS_ALL_IN, CGTexasAllIn.class);
		map.put(MessageType.CG_TEXAS_GIVE_UP, CGTexasGiveUp.class);
		map.put(MessageType.CG_TEXAS_SEAT, CGTexasSeat.class);
		map.put(MessageType.CG_TEXAS_EXIT, CGTexasExit.class);
		map.put(MessageType.CG_TEXAS_AUTO, CGTexasAuto.class);
		map.put(MessageType.CG_TEXAS_COMPLEMENT, CGTexasComplement.class);
		map.put(MessageType.CG_TEXAS_TIPS, CGTexasTips.class);
		map.put(MessageType.CG_TEXAS_PEOPLE_SETTING, CGTexasPeopleSetting.class);
		map.put(MessageType.CG_TEXAS_QUICK_START, CGTexasQuickStart.class);
		map.put(MessageType.CG_TEXAS_SNG_LIST, CGTexasSngList.class);
		map.put(MessageType.CG_JOIN_TEXAS_SNG, CGJoinTexasSng.class);
		map.put(MessageType.CG_TEXAS_VIP_LIST, CGTexasVipList.class);
		map.put(MessageType.CG_JOIN_TEXAS_VIP, CGJoinTexasVip.class);
		map.put(MessageType.CG_HUMAN_TEXAS_INFO_DATA_SEARCH, CGHumanTexasInfoDataSearch.class);
		return map;
	}

}
