package com.gameserver.luckyspin.msg;

import java.util.HashMap;
import java.util.Map;

import com.gameserver.common.msg.MessageType;
import com.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class LuckyspinMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_LUCKY_SPIN, CGLuckySpin.class);
		map.put(MessageType.CG_LUCKY_MATCH, CGLuckyMatch.class);
		map.put(MessageType.CG_BIG_ZHUANPAN, CGBigZhuanpan.class);
		map.put(MessageType.CG_SPIN_ZHUANPAN, CGSpinZhuanpan.class);
		return map;
	}

}
