package com.gameserver.collect.msg;

import java.util.HashMap;
import java.util.Map;

import com.gameserver.common.msg.MessageType;
import com.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class CollectMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_CHARM_EXCHANGE, CGCharmExchange.class);
		map.put(MessageType.CG_COLLECT_INIT, CGCollectInit.class);
		map.put(MessageType.CG_RAFFLE, CGRaffle.class);
		map.put(MessageType.CG_CARD_EXCHANGE, CGCardExchange.class);
		return map;
	}

}
