package com.gameserver.baccart.msg;

import java.util.HashMap;
import java.util.Map;

import com.gameserver.common.msg.MessageType;
import com.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class BaccartMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_BACCART_LIST, CGBaccartList.class);
		map.put(MessageType.CG_BACCART_BET, CGBaccartBet.class);
		map.put(MessageType.CG_BACCART_JOIN, CGBaccartJoin.class);
		map.put(MessageType.CG_BACCART_STAND, CGBaccartStand.class);
		map.put(MessageType.CG_BACCART_SEAT, CGBaccartSeat.class);
		map.put(MessageType.CG_BACCART_EXIT, CGBaccartExit.class);
		map.put(MessageType.CG_HUMAN_BACCART, CGHumanBaccart.class);
		map.put(MessageType.CG_BACCART_AUTO, CGBaccartAuto.class);
		map.put(MessageType.CG_BACCART_COMPLEMENT, CGBaccartComplement.class);
		map.put(MessageType.CG_BACCART_REVIVE, CGBaccartRevive.class);
		map.put(MessageType.CG_BACCARAT_QUICK_START, CGBaccaratQuickStart.class);
		return map;
	}

}
