package com.gameserver.player.msg;

import java.util.HashMap;
import java.util.Map;

import com.gameserver.common.msg.MessageType;
import com.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class PlayerMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_QUERY_PLAYER_INFO, CGQueryPlayerInfo.class);
		map.put(MessageType.CG_QUERY_PLAYER_INFO_NAME, CGQueryPlayerInfoName.class);
		map.put(MessageType.CG_CHECK_PLAYER_LOGIN, CGCheckPlayerLogin.class);
		map.put(MessageType.CG_PLAYER_ENTER, CGPlayerEnter.class);
		map.put(MessageType.CG_ENTER_SCENE, CGEnterScene.class);
		map.put(MessageType.CG_CLIENT_VERSION, CGClientVersion.class);
		return map;
	}

}
