package com.gameserver.activity.msg;

import java.util.HashMap;
import java.util.Map;

import com.gameserver.common.msg.MessageType;
import com.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class ActivityMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_ACTIVITY_LIST, CGActivityList.class);
		map.put(MessageType.CG_ACTIVITY_PROGRESS, CGActivityProgress.class);
		map.put(MessageType.CG_GET_ACTIVITY_REWARD, CGGetActivityReward.class);
		map.put(MessageType.CG_MONTH_WEEK_LEFT_TIME, CGMonthWeekLeftTime.class);
		map.put(MessageType.CG_STILL_HAVE_ACTIVITY_GOLD, CGStillHaveActivityGold.class);
		map.put(MessageType.CG_FUNCTION, CGFunction.class);
		return map;
	}

}
