package com.gameserver.newbie.msg;

import java.util.HashMap;
import java.util.Map;

import com.gameserver.common.msg.MessageType;
import com.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class NewbieMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_SAVE_POINT, CGSavePoint.class);
		map.put(MessageType.CG_GET_SAVE_POINT, CGGetSavePoint.class);
		map.put(MessageType.CG_SLOT_NEWBIE, CGSlotNewbie.class);
		return map;
	}

}
