package com.gameserver.club.msg;

import java.util.HashMap;
import java.util.Map;

import com.gameserver.common.msg.MessageType;
import com.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class ClubMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_CLUB_PANEL, CGClubPanel.class);
		map.put(MessageType.CG_CLUB_CREATE, CGClubCreate.class);
		map.put(MessageType.CG_CLUB_SIGN, CGClubSign.class);
		map.put(MessageType.CG_CLUB_DONATE, CGClubDonate.class);
		map.put(MessageType.CG_CLUB_SEARCH, CGClubSearch.class);
		map.put(MessageType.CG_CLUB_NOTE_PANEL, CGClubNotePanel.class);
		map.put(MessageType.CG_CLUB_NOTE_SEND, CGClubNoteSend.class);
		map.put(MessageType.CG_CLUB_NOTE_SEND_GIFT, CGClubNoteSendGift.class);
		map.put(MessageType.CG_CLUB_INVATE_LIST, CGClubInvateList.class);
		map.put(MessageType.CG_CLUB_RANKING_lIST, CGClubRankingList.class);
		map.put(MessageType.CG_CLUB_JOIN, CGClubJoin.class);
		map.put(MessageType.CG_CLUB_NOT_JOIN, CGClubNotJoin.class);
		map.put(MessageType.CG_CLUB_APPLY_LIST, CGClubApplyList.class);
		map.put(MessageType.CG_CLUB_APPLY_OP, CGClubApplyOp.class);
		map.put(MessageType.CG_CLUB_INVATE, CGClubInvate.class);
		map.put(MessageType.CG_CLUB_JOIN2, CGClubJoin2.class);
		map.put(MessageType.CG_CLUB_EDIT, CGClubEdit.class);
		map.put(MessageType.CG_CLUB_CHANGE_NAME, CGClubChangeName.class);
		map.put(MessageType.CG_CLUB_LEAVE, CGClubLeave.class);
		map.put(MessageType.CG_CLUB_KICK, CGClubKick.class);
		map.put(MessageType.CG_CLUB_PROMATE, CGClubPromate.class);
		map.put(MessageType.CG_CLUB_INFO_GET, CGClubInfoGet.class);
		map.put(MessageType.CG_CLUB_NOTE_DELETE, CGClubNoteDelete.class);
		map.put(MessageType.CG_CLUB_GET_GIFT, CGClubGetGift.class);
		map.put(MessageType.CG_CLUB_TANHE, CGClubTanhe.class);
		map.put(MessageType.CG_CLUB_TANHE_STATE, CGClubTanheState.class);
		map.put(MessageType.CG_CLUB_TANHE_VOTE, CGClubTanheVote.class);
		return map;
	}

}
