package com.gameserver.worldboss.msg;

import java.util.HashMap;
import java.util.Map;

import com.gameserver.common.msg.MessageType;
import com.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class WorldbossMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_OPEN_PANEL, CGOpenPanel.class);
		map.put(MessageType.CG_GET_BOSS_INFO, CGGetBossInfo.class);
		map.put(MessageType.CG_GET_RANK_INFO, CGGetRankInfo.class);
		map.put(MessageType.CG_REFRESH_BOSS_INFO, CGRefreshBossInfo.class);
		map.put(MessageType.CG_BOSS_START_END_INFO, CGBossStartEndInfo.class);
		map.put(MessageType.CG_RETURN_BLOOD, CGReturnBlood.class);
		map.put(MessageType.CG_BEFORE_START, CGBeforeStart.class);
		return map;
	}

}
